#!/usr/bin/make
#
# $Id: Makefile,v 1.5 2004/09/04 03:15:45 teshields Exp $
#
.PHONY : install

all : reset.a68 ca68
	echo "Nothing to be done for all"

install :
	$(INSTALLPROG) -p reset.a68 ca68 $(BINDIR)
