Version 2109930912
Initialise mmdir/mm_default_database.mmd
Define default_debug "off"
Define default_star_chars "1234ABCD"
Define edit_command "editor"
Define libdir "homedir/lib"
Define notify_at_go "off"
Define dir1 "."
Define libd1 "."
Define libd2 "'rootdir'"
Define libl1 "'rootdir'"
Define libr1 "."
Decs standard 1 standard.a68
